project_name: Oppai_benchmark
before:
  hooks:
    - go mod tidy

checksum:
  name_template: "{{ .ProjectName }}_linux_checksums.txt"

builds:
  - main: .
    id: Oppai_benchmark
    binary: Oppai_benchmark
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - GO386=387
    goos:
      - linux
    goarch:
      - 386

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

release:
  prerelease: auto
