name: release
on:
  push:
    tags:
      - "v*"
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.17"]
        _386: [""]
        arch: ["amd64"]
        os: ["linux", "windows", "darwin"]
        include:
          - version: "1.15"
            _386: "387"
            arch: "386"
            os: "windows"

          - version: "1.15"
            _386: "387"
            arch: "386"
            os: "linux"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.version }}

      - name: build
        run: |
          go build
          zip -r lw_oppai_benchmark-${GOOS}-${GOARCH}${GO386:+"-$GO386"}.zip lw_oppai_benchmark*
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GO386: ${{ matrix._386 }}

  release:
    needs: build
    steps:
      - name: pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.zip
